# Generated by Django 4.2.3 on 2023-08-07 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineshop',
            name='image',
            field=models.ImageField(default=1, upload_to='online_shop/', verbose_name='Изображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineshop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
