# Generated by Django 4.2.3 on 2023-07-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0003_alter_advertisement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table=None,
        ),
    ]
